name: CI

on:
  pull_request:
    branches: [main]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Git clone
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Npm install
      run: npm ci

    - name: Npx run
      run: npx cypress run --headless

    - name: Create test summary
      uses: test-summary/action@v1.0
      if: always()
      with:
        paths: reports/*.xml

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "reports/*.xml"

    - name: Artifacts
      on: [push]
      jobs:
        cypress-run:
          runs-on: ubuntu-20.04
          name: Artifacts
          steps:
            # - uses: actions/checkout@v2
            # - uses: cypress-io/github-action@v4
            - uses: actions/upload-artifact@v2
              if: failure()
              with:
                name: cypress-snapshots
                path: cypress/snapshots
